<!-- model: nvidia/nemotron-nano-9b-v2:free | category: code | run: 20260713T105517Z -->
<!-- PROMPT -->
Write a self‑contained Java program that defines a public class named `CyclicBarrierPipeline` implementing a multi‑stage data processing pipeline coordinated with a `java.util.concurrent.CyclicBarrier`. The pipeline should have a configurable number of stages (at least three) and a configurable number of worker threads per stage. Each worker thread processes a chunk of data, waits at the barrier for its peers in the same stage, then passes its results to the next stage. The implementation must ensure thread‑safety, avoid deadlocks, and correctly handle exceptions thrown by any worker (propagating them to a central coordinator). Include comprehensive Javadoc explaining the concurrency strategy, barrier reuse, and shutdown procedure. Additionally, provide a full suite of JUnit 5 tests that verify:
• Correct functional output for a known input across all stages.
• Proper barrier synchronization (e.g., no thread proceeds to the next stage before all have arrived).
• Handling of worker exceptions (the pipeline should abort gracefully and report the error).
• Stress test with high thread counts and large data volumes to detect race conditions or livelocks.
Do not implement the solution; only output the prompt text.
<!-- RESPONSE -->
**Prompt Text:**  
You are tasked with designing a self-contained Java program named `CyclicBarrierPipeline` that implements a multi-stage data processing pipeline using `java.util.concurrent.CyclicBarrier`. The pipeline must support a configurable number of stages (≥3) and a configurable number of worker threads per stage. Each worker thread processes a data chunk, synchronizes at a stage-specific barrier, and passes results to the next stage. Your implementation must ensure thread-safety, prevent deadlocks, and propagate exceptions to a central coordinator. Additionally, you must provide comprehensive Javadoc explaining the concurrency strategy, barrier reuse mechanism, and shutdown procedure. Finally, write a full JUnit 5 test suite to validate functional correctness, barrier synchronization, exception handling, and stress-testing under high load. Ensure all requirements are met without implementing the solution itself.
